// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"time"
)

type ApiKey struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	PrefixLast4 string         `json:"prefix_last4"`
	KeyHash     string         `json:"key_hash"`
	Scopes      string         `json:"scopes"`
	ProjectIds  string         `json:"project_ids"`
	CreatedAt   string         `json:"created_at"`
	ExpiresAt   sql.NullString `json:"expires_at"`
	LastUsedAt  sql.NullString `json:"last_used_at"`
	RevokedAt   sql.NullString `json:"revoked_at"`
}

type ApiUsageLog struct {
	ID         int64  `json:"id"`
	ApiKeyID   string `json:"api_key_id"`
	Method     string `json:"method"`
	Path       string `json:"path"`
	StatusCode int64  `json:"status_code"`
	LatencyMs  int64  `json:"latency_ms"`
	Ip         string `json:"ip"`
	UserAgent  string `json:"user_agent"`
	CreatedAt  string `json:"created_at"`
}

type AuthMagicLink struct {
	ID        int64        `json:"id"`
	TokenHash string       `json:"token_hash"`
	Email     string       `json:"email"`
	ExpiresAt time.Time    `json:"expires_at"`
	UsedAt    sql.NullTime `json:"used_at"`
	CreatedAt time.Time    `json:"created_at"`
}

type AuthSession struct {
	ID        int64     `json:"id"`
	TokenHash string    `json:"token_hash"`
	Email     string    `json:"email"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type BacklogAdmissionDecline struct {
	ID              string          `json:"id"`
	ProjectID       string          `json:"project_id"`
	IssueID         string          `json:"issue_id"`
	IssueIdentifier string          `json:"issue_identifier"`
	IssueURL        string          `json:"issue_url"`
	Fingerprint     string          `json:"fingerprint"`
	Reason          string          `json:"reason"`
	Detail          string          `json:"detail"`
	CreatedAt       string          `json:"created_at"`
	CommentedAt     sql.NullString  `json:"commented_at"`
	Confidence      sql.NullFloat64 `json:"confidence"`
	FailedDimension string          `json:"failed_dimension"`
	FailedCriterion string          `json:"failed_criterion"`
}

type BacklogAdmissionDownstreamOutcome struct {
	ProposalID       string         `json:"proposal_id"`
	ProjectID        string         `json:"project_id"`
	IssueID          string         `json:"issue_id"`
	CompletedAt      sql.NullString `json:"completed_at"`
	ReworkCount      int64          `json:"rework_count"`
	ReviewChurnCount int64          `json:"review_churn_count"`
	SpendUsd         float64        `json:"spend_usd"`
	UpdatedAt        string         `json:"updated_at"`
}

type BacklogAdmissionMalformedResult struct {
	ID                   int64          `json:"id"`
	ProjectID            string         `json:"project_id"`
	IssueID              string         `json:"issue_id"`
	IssueIdentifier      string         `json:"issue_identifier"`
	IssueURL             string         `json:"issue_url"`
	CandidateFingerprint string         `json:"candidate_fingerprint"`
	PromptFingerprint    string         `json:"prompt_fingerprint"`
	ProposalFingerprint  string         `json:"proposal_fingerprint"`
	ErrorFingerprint     string         `json:"error_fingerprint"`
	ErrorClass           string         `json:"error_class"`
	ErrorCode            string         `json:"error_code"`
	OutputExcerpt        string         `json:"output_excerpt"`
	AttemptCount         int64          `json:"attempt_count"`
	Status               string         `json:"status"`
	FirstSeenAt          string         `json:"first_seen_at"`
	LastSeenAt           string         `json:"last_seen_at"`
	ResolvedAt           sql.NullString `json:"resolved_at"`
}

type BacklogAdmissionProposal struct {
	ID                 string         `json:"id"`
	ProjectID          string         `json:"project_id"`
	IssueID            string         `json:"issue_id"`
	IssueIdentifier    string         `json:"issue_identifier"`
	IssueURL           string         `json:"issue_url"`
	TargetState        string         `json:"target_state"`
	Fingerprint        string         `json:"fingerprint"`
	CriteriaSection    string         `json:"criteria_section"`
	CriteriaText       string         `json:"criteria_text"`
	FindingsJson       string         `json:"findings_json"`
	Confidence         float64        `json:"confidence"`
	Status             string         `json:"status"`
	CreatedAt          string         `json:"created_at"`
	ExpiresAt          string         `json:"expires_at"`
	ResolvedAt         sql.NullString `json:"resolved_at"`
	CommentedAt        sql.NullString `json:"commented_at"`
	DecisionCommentID  sql.NullString `json:"decision_comment_id"`
	DecisionActorLogin sql.NullString `json:"decision_actor_login"`
	DecisionActorKind  sql.NullString `json:"decision_actor_kind"`
	TransitionAt       sql.NullString `json:"transition_at"`
	DecisionSeconds    sql.NullInt64  `json:"decision_seconds"`
	ResolutionReason   sql.NullString `json:"resolution_reason"`
	RecommendedEffort  sql.NullString `json:"recommended_effort"`
	EffortRationale    sql.NullString `json:"effort_rationale"`
}

type BacklogAdmissionRun struct {
	ID                   int64          `json:"id"`
	ProjectID            string         `json:"project_id"`
	ScheduledFor         string         `json:"scheduled_for"`
	StartedAt            string         `json:"started_at"`
	CompletedAt          string         `json:"completed_at"`
	Outcome              string         `json:"outcome"`
	DeferredReason       sql.NullString `json:"deferred_reason"`
	CandidatesFoundCount int64          `json:"candidates_found_count"`
	CandidatesCount      int64          `json:"candidates_count"`
	ProposedCount        int64          `json:"proposed_count"`
	SkippedJson          string         `json:"skipped_json"`
	TruncatedJson        string         `json:"truncated_json"`
	IssuesJson           string         `json:"issues_json"`
	Error                sql.NullString `json:"error"`
	ProposalReason       sql.NullString `json:"proposal_reason"`
	ResumeAt             sql.NullString `json:"resume_at"`
	MalformedJson        string         `json:"malformed_json"`
}

type BudgetOverride struct {
	ProjectID      string          `json:"project_id"`
	PerDayMaxUsd   sql.NullFloat64 `json:"per_day_max_usd"`
	PerIssueMaxUsd sql.NullFloat64 `json:"per_issue_max_usd"`
	ExpiresAt      string          `json:"expires_at"`
	CreatedAt      string          `json:"created_at"`
	Reason         string          `json:"reason"`
}

type CodexSession struct {
	ID                           int64          `json:"id"`
	RunID                        sql.NullInt64  `json:"run_id"`
	IssueID                      sql.NullString `json:"issue_id"`
	Identifier                   sql.NullString `json:"identifier"`
	IssueURL                     sql.NullString `json:"issue_url"`
	StartedAt                    sql.NullString `json:"started_at"`
	CompletedAt                  sql.NullString `json:"completed_at"`
	Turns                        int64          `json:"turns"`
	InputTokens                  int64          `json:"input_tokens"`
	OutputTokens                 int64          `json:"output_tokens"`
	TotalTokens                  int64          `json:"total_tokens"`
	RuntimeSeconds               int64          `json:"runtime_seconds"`
	FinalState                   sql.NullString `json:"final_state"`
	Model                        sql.NullString `json:"model"`
	CachedInputTokens            sql.NullInt64  `json:"cached_input_tokens"`
	ReasoningOutputTokens        sql.NullInt64  `json:"reasoning_output_tokens"`
	ModelContextWindow           sql.NullInt64  `json:"model_context_window"`
	RequestedModel               sql.NullString `json:"requested_model"`
	AgentBackendID               sql.NullString `json:"agent_backend_id"`
	AgentBackendKind             sql.NullString `json:"agent_backend_kind"`
	AgentRole                    sql.NullString `json:"agent_role"`
	ProviderThreadID             sql.NullString `json:"provider_thread_id"`
	ProviderSessionID            sql.NullString `json:"provider_session_id"`
	ResumedFromSessionID         sql.NullInt64  `json:"resumed_from_session_id"`
	WorkAttemptID                sql.NullInt64  `json:"work_attempt_id"`
	AgentRoute                   sql.NullString `json:"agent_route"`
	Provider                     sql.NullString `json:"provider"`
	ProviderProvenance           sql.NullString `json:"provider_provenance"`
	RequestedModelProvenance     sql.NullString `json:"requested_model_provenance"`
	ModelProvenance              sql.NullString `json:"model_provenance"`
	ReasoningEffort              sql.NullString `json:"reasoning_effort"`
	ReasoningEffortProvenance    sql.NullString `json:"reasoning_effort_provenance"`
	ServiceTier                  sql.NullString `json:"service_tier"`
	ServiceTierProvenance        sql.NullString `json:"service_tier_provenance"`
	IdentityObservedAt           sql.NullString `json:"identity_observed_at"`
	OrphanRecoveryOutcome        sql.NullString `json:"orphan_recovery_outcome"`
	SkillDraftProposed           int64          `json:"skill_draft_proposed"`
	OrphanRecoveryFallbackReason sql.NullString `json:"orphan_recovery_fallback_reason"`
	WorkerPid                    sql.NullInt64  `json:"worker_pid"`
	WorkerPgid                   sql.NullInt64  `json:"worker_pgid"`
	WorkerStartedAt              sql.NullString `json:"worker_started_at"`
	WorkerReapedAt               sql.NullString `json:"worker_reaped_at"`
	WorkerReapOutcome            sql.NullString `json:"worker_reap_outcome"`
	ProjectID                    sql.NullString `json:"project_id"`
	WorkerReapReason             sql.NullString `json:"worker_reap_reason"`
	WorkerCleanupRoot            sql.NullString `json:"worker_cleanup_root"`
	WorkerCleanupPath            sql.NullString `json:"worker_cleanup_path"`
	RuntimeIdentityJson          sql.NullString `json:"runtime_identity_json"`
}

type DetentRun struct {
	ID                   int64          `json:"id"`
	StartedAt            string         `json:"started_at"`
	StoppedAt            sql.NullString `json:"stopped_at"`
	RestartReason        sql.NullString `json:"restart_reason"`
	PeakConcurrentAgents int64          `json:"peak_concurrent_agents"`
	SessionsLaunched     int64          `json:"sessions_launched"`
	InputTokens          int64          `json:"input_tokens"`
	OutputTokens         int64          `json:"output_tokens"`
	TotalTokens          int64          `json:"total_tokens"`
	RuntimeSeconds       int64          `json:"runtime_seconds"`
}

type EfficiencyReceipt struct {
	ID                    int64          `json:"id"`
	ProjectID             string         `json:"project_id"`
	IssueID               string         `json:"issue_id"`
	Identifier            sql.NullString `json:"identifier"`
	IssueURL              sql.NullString `json:"issue_url"`
	PrNumber              sql.NullInt64  `json:"pr_number"`
	Sessions              int64          `json:"sessions"`
	Attempts              int64          `json:"attempts"`
	InputTokens           int64          `json:"input_tokens"`
	CachedInputTokens     int64          `json:"cached_input_tokens"`
	OutputTokens          int64          `json:"output_tokens"`
	ReasoningOutputTokens int64          `json:"reasoning_output_tokens"`
	TotalTokens           int64          `json:"total_tokens"`
	EstimatedCostUsd      float64        `json:"estimated_cost_usd"`
	FirstDispatchedAt     string         `json:"first_dispatched_at"`
	CompletedAt           string         `json:"completed_at"`
	WallSeconds           int64          `json:"wall_seconds"`
	WorkingSeconds        int64          `json:"working_seconds"`
	GateWaitSeconds       int64          `json:"gate_wait_seconds"`
	MergeTrainSeconds     int64          `json:"merge_train_seconds"`
	ParkedSeconds         int64          `json:"parked_seconds"`
	Redispatches          int64          `json:"redispatches"`
	BreakerTrips          int64          `json:"breaker_trips"`
	CiReruns              int64          `json:"ci_reruns"`
	TokensBaseline        float64        `json:"tokens_baseline"`
	SessionsBaseline      float64        `json:"sessions_baseline"`
	DwellBaselineSeconds  float64        `json:"dwell_baseline_seconds"`
	TokensAnomaly         int64          `json:"tokens_anomaly"`
	SessionsAnomaly       int64          `json:"sessions_anomaly"`
	DwellAnomaly          int64          `json:"dwell_anomaly"`
	InProgress            int64          `json:"in_progress"`
	RefreshedAt           string         `json:"refreshed_at"`
}

type FairShareUsage struct {
	ProjectID      string `json:"project_id"`
	Weight         int64  `json:"weight"`
	Dispatches     int64  `json:"dispatches"`
	RuntimeSeconds int64  `json:"runtime_seconds"`
	UpdatedAt      string `json:"updated_at"`
}

type HealthNotificationState struct {
	Identity  string `json:"identity"`
	StateJson string `json:"state_json"`
	UpdatedAt string `json:"updated_at"`
}

type IssueParkAcknowledgement struct {
	ProjectID      string         `json:"project_id"`
	IssueKey       string         `json:"issue_key"`
	IssueID        sql.NullString `json:"issue_id"`
	Identifier     sql.NullString `json:"identifier"`
	IssueURL       sql.NullString `json:"issue_url"`
	ParkSequence   int64          `json:"park_sequence"`
	AcknowledgedAt string         `json:"acknowledged_at"`
}

type IssueProgressCredit struct {
	ProjectID  string         `json:"project_id"`
	IssueKey   string         `json:"issue_key"`
	IssueID    sql.NullString `json:"issue_id"`
	Identifier sql.NullString `json:"identifier"`
	IssueURL   sql.NullString `json:"issue_url"`
	CreditedAt string         `json:"credited_at"`
}

type LaneMutationReceipt struct {
	ID            int64          `json:"id"`
	ProjectID     string         `json:"project_id"`
	IssueID       string         `json:"issue_id"`
	WorkAttemptID int64          `json:"work_attempt_id"`
	Generation    int64          `json:"generation"`
	Disposition   string         `json:"disposition"`
	FromState     string         `json:"from_state"`
	ToState       string         `json:"to_state"`
	Reason        string         `json:"reason"`
	TrackerResult string         `json:"tracker_result"`
	RequestedAt   string         `json:"requested_at"`
	ResolvedAt    sql.NullString `json:"resolved_at"`
	ConsumedAt    sql.NullString `json:"consumed_at"`
	ErrorMessage  sql.NullString `json:"error_message"`
}

type MergeRequiredCheckStreak struct {
	ProjectID                 string `json:"project_id"`
	IssueID                   string `json:"issue_id"`
	Repository                string `json:"repository"`
	PrNumber                  int64  `json:"pr_number"`
	CheckName                 string `json:"check_name"`
	RequiredChecksFingerprint string `json:"required_checks_fingerprint"`
	ConsecutiveMissing        int64  `json:"consecutive_missing"`
	UpdatedAt                 string `json:"updated_at"`
	HeadSha                   string `json:"head_sha"`
}

type ProjectDispatchStatus struct {
	ProjectID              string         `json:"project_id"`
	CandidateCount         int64          `json:"candidate_count"`
	CandidateFingerprint   string         `json:"candidate_fingerprint"`
	SelectedCount          int64          `json:"selected_count"`
	SkippedCount           int64          `json:"skipped_count"`
	WaitReason             sql.NullString `json:"wait_reason"`
	AllSkippedSince        sql.NullString `json:"all_skipped_since"`
	LastSelectedAt         sql.NullString `json:"last_selected_at"`
	ObservedAt             string         `json:"observed_at"`
	EligibleCandidateCount int64          `json:"eligible_candidate_count"`
	WaitReasonCode         sql.NullString `json:"wait_reason_code"`
}

type ProvenanceAttributionBoundary struct {
	ID               int64  `json:"id"`
	TrustworthySince string `json:"trustworthy_since"`
}

type RetroRun struct {
	ID            int64          `json:"id"`
	ProjectID     string         `json:"project_id"`
	Trigger       string         `json:"trigger"`
	StartedAt     string         `json:"started_at"`
	CompletedAt   string         `json:"completed_at"`
	FindingsCount int64          `json:"findings_count"`
	FiledCount    int64          `json:"filed_count"`
	UpdatedCount  int64          `json:"updated_count"`
	Error         sql.NullString `json:"error"`
	EventDay      string         `json:"event_day"`
}

type RoutineFinding struct {
	ProjectID   string `json:"project_id"`
	RoutineName string `json:"routine_name"`
	IssueID     string `json:"issue_id"`
	Identifier  string `json:"identifier"`
	Url         string `json:"url"`
	Open        int64  `json:"open"`
}

type RoutineRun struct {
	ID                int64          `json:"id"`
	ProjectID         string         `json:"project_id"`
	RoutineName       string         `json:"routine_name"`
	ScheduledFor      string         `json:"scheduled_for"`
	StartedAt         string         `json:"started_at"`
	CompletedAt       string         `json:"completed_at"`
	FiledCount        int64          `json:"filed_count"`
	DeduplicatedCount int64          `json:"deduplicated_count"`
	IssuesJson        string         `json:"issues_json"`
	Error             sql.NullString `json:"error"`
	ProposedCount     int64          `json:"proposed_count"`
	LimitedCount      int64          `json:"limited_count"`
}

type ScheduledRun struct {
	ID           int64          `json:"id"`
	ProjectID    string         `json:"project_id"`
	ScheduleID   string         `json:"schedule_id"`
	ScheduledFor string         `json:"scheduled_for"`
	StartedAt    string         `json:"started_at"`
	CompletedAt  string         `json:"completed_at"`
	Error        sql.NullString `json:"error"`
}

type SchedulerDecision struct {
	ID                     int64          `json:"id"`
	ProjectID              string         `json:"project_id"`
	IssueID                sql.NullString `json:"issue_id"`
	Identifier             sql.NullString `json:"identifier"`
	IssueURL               sql.NullString `json:"issue_url"`
	PrNumber               sql.NullInt64  `json:"pr_number"`
	Repo                   sql.NullString `json:"repo"`
	Lane                   sql.NullString `json:"lane"`
	QueuePosition          int64          `json:"queue_position"`
	Result                 string         `json:"result"`
	Reason                 sql.NullString `json:"reason"`
	Selected               int64          `json:"selected"`
	Retry                  int64          `json:"retry"`
	AttemptNumber          int64          `json:"attempt_number"`
	WorkerHost             sql.NullString `json:"worker_host"`
	DecisionAt             string         `json:"decision_at"`
	WaitReason             sql.NullString `json:"wait_reason"`
	CapacitySnapshotJson   string         `json:"capacity_snapshot_json"`
	GithubRateSnapshotJson string         `json:"github_rate_snapshot_json"`
	MetadataJson           string         `json:"metadata_json"`
}

type SecurityAuditDisposition struct {
	ID              int64  `json:"id"`
	AuditRunID      int64  `json:"audit_run_id"`
	FindingID       string `json:"finding_id"`
	Status          string `json:"status"`
	Evidence        string `json:"evidence"`
	ServiceIdentity string `json:"service_identity"`
	RecordedAt      string `json:"recorded_at"`
}

type SecurityAuditRun struct {
	ID                 int64          `json:"id"`
	InvocationID       string         `json:"invocation_id"`
	ProjectID          string         `json:"project_id"`
	IssueID            string         `json:"issue_id"`
	Identifier         string         `json:"identifier"`
	IssueURL           string         `json:"issue_url"`
	Repository         string         `json:"repository"`
	PrNumber           int64          `json:"pr_number"`
	BaseSha            string         `json:"base_sha"`
	HeadSha            string         `json:"head_sha"`
	ServiceIdentity    string         `json:"service_identity"`
	ReviewerVersion    string         `json:"reviewer_version"`
	ReviewerDigest     string         `json:"reviewer_digest"`
	AuthenticationMode string         `json:"authentication_mode"`
	WorkerPid          int64          `json:"worker_pid"`
	WorkerPgid         int64          `json:"worker_pgid"`
	WorkerStartedAt    sql.NullString `json:"worker_started_at"`
	ProviderThreadID   string         `json:"provider_thread_id"`
	ProviderSessionID  string         `json:"provider_session_id"`
	ExitStatus         string         `json:"exit_status"`
	Failure            string         `json:"failure"`
	OutputDigest       string         `json:"output_digest"`
	OutputBytes        int64          `json:"output_bytes"`
	Verdict            string         `json:"verdict"`
	Summary            string         `json:"summary"`
	FindingsJson       string         `json:"findings_json"`
	Attempt            int64          `json:"attempt"`
	StartedAt          string         `json:"started_at"`
	CompletedAt        string         `json:"completed_at"`
	RecordedAt         string         `json:"recorded_at"`
}

type SessionProgress struct {
	SessionID       int64  `json:"session_id"`
	ObservationJson string `json:"observation_json"`
}

type StalenessWarningState struct {
	ProjectID      string         `json:"project_id"`
	WarningID      string         `json:"warning_id"`
	RemindedAt     sql.NullString `json:"reminded_at"`
	AcknowledgedAt sql.NullString `json:"acknowledged_at"`
	LastSeenAt     sql.NullString `json:"last_seen_at"`
}

type UsageEvent struct {
	ID                     int64           `json:"id"`
	ProjectID              string          `json:"project_id"`
	RunID                  sql.NullInt64   `json:"run_id"`
	SessionID              sql.NullInt64   `json:"session_id"`
	IssueID                sql.NullString  `json:"issue_id"`
	Identifier             sql.NullString  `json:"identifier"`
	PrNumber               sql.NullInt64   `json:"pr_number"`
	Model                  string          `json:"model"`
	InputTokens            int64           `json:"input_tokens"`
	OutputTokens           int64           `json:"output_tokens"`
	TotalTokens            int64           `json:"total_tokens"`
	RuntimeSeconds         int64           `json:"runtime_seconds"`
	StartedAt              string          `json:"started_at"`
	FinishedAt             string          `json:"finished_at"`
	EventDay               string          `json:"event_day"`
	Outcome                string          `json:"outcome"`
	CostUsd                float64         `json:"cost_usd"`
	CachedInputTokens      sql.NullInt64   `json:"cached_input_tokens"`
	ReasoningOutputTokens  sql.NullInt64   `json:"reasoning_output_tokens"`
	ModelContextWindow     sql.NullInt64   `json:"model_context_window"`
	ProjectedCostUsd       sql.NullFloat64 `json:"projected_cost_usd"`
	ProjectionOvershootUsd float64         `json:"projection_overshoot_usd"`
}

type ValidatorVerdict struct {
	ID              int64          `json:"id"`
	ProjectID       string         `json:"project_id"`
	IssueID         string         `json:"issue_id"`
	HeadSha         string         `json:"head_sha"`
	Identifier      sql.NullString `json:"identifier"`
	IssueURL        sql.NullString `json:"issue_url"`
	PrNumber        sql.NullInt64  `json:"pr_number"`
	Submitted       int64          `json:"submitted"`
	Verdict         string         `json:"verdict"`
	Score           float64        `json:"score"`
	Summary         sql.NullString `json:"summary"`
	FindingsJson    string         `json:"findings_json"`
	Commented       int64          `json:"commented"`
	RecordedAt      string         `json:"recorded_at"`
	UpdatedAt       string         `json:"updated_at"`
	FailureAttempts int64          `json:"failure_attempts"`
	NextRetryAt     sql.NullString `json:"next_retry_at"`
}

type WorkAttempt struct {
	ID                     int64          `json:"id"`
	ProjectID              string         `json:"project_id"`
	IssueID                sql.NullString `json:"issue_id"`
	Identifier             sql.NullString `json:"identifier"`
	IssueURL               sql.NullString `json:"issue_url"`
	PrNumber               sql.NullInt64  `json:"pr_number"`
	Repo                   sql.NullString `json:"repo"`
	WorkerType             string         `json:"worker_type"`
	WorkerHost             sql.NullString `json:"worker_host"`
	Lane                   sql.NullString `json:"lane"`
	AttemptNumber          int64          `json:"attempt_number"`
	Status                 string         `json:"status"`
	StartedAt              string         `json:"started_at"`
	LeaseExpiresAt         sql.NullString `json:"lease_expires_at"`
	HeartbeatAt            sql.NullString `json:"heartbeat_at"`
	CompletedAt            sql.NullString `json:"completed_at"`
	TerminalState          sql.NullString `json:"terminal_state"`
	ErrorClass             sql.NullString `json:"error_class"`
	ErrorMessage           sql.NullString `json:"error_message"`
	Phase                  sql.NullString `json:"phase"`
	StatusMessage          sql.NullString `json:"status_message"`
	CurrentStep            sql.NullInt64  `json:"current_step"`
	TotalSteps             sql.NullInt64  `json:"total_steps"`
	ProgressPercent        sql.NullInt64  `json:"progress_percent"`
	CurrentCommand         sql.NullString `json:"current_command"`
	WaitReason             sql.NullString `json:"wait_reason"`
	GithubRateSnapshotJson string         `json:"github_rate_snapshot_json"`
	CiState                sql.NullString `json:"ci_state"`
	CapacitySnapshotJson   string         `json:"capacity_snapshot_json"`
	WorkerMetadataJson     string         `json:"worker_metadata_json"`
	MetricsJson            string         `json:"metrics_json"`
	NextAction             sql.NullString `json:"next_action"`
	DetentSessionID        sql.NullInt64  `json:"detent_session_id"`
	ProviderSessionID      sql.NullString `json:"provider_session_id"`
	RuntimeIdentityJson    string         `json:"runtime_identity_json"`
}

type WorkflowPhaseEvent struct {
	ID                    int64          `json:"id"`
	ProjectID             string         `json:"project_id"`
	RunID                 sql.NullInt64  `json:"run_id"`
	SessionID             sql.NullInt64  `json:"session_id"`
	IssueID               sql.NullString `json:"issue_id"`
	Identifier            sql.NullString `json:"identifier"`
	IssueURL              sql.NullString `json:"issue_url"`
	PrNumber              sql.NullInt64  `json:"pr_number"`
	PhaseType             string         `json:"phase_type"`
	PhaseName             string         `json:"phase_name"`
	PreviousPhaseName     sql.NullString `json:"previous_phase_name"`
	Reason                sql.NullString `json:"reason"`
	Status                sql.NullString `json:"status"`
	StartedAt             string         `json:"started_at"`
	FinishedAt            sql.NullString `json:"finished_at"`
	DurationSeconds       int64          `json:"duration_seconds"`
	EventDay              string         `json:"event_day"`
	CommandName           sql.NullString `json:"command_name"`
	ExitCode              sql.NullInt64  `json:"exit_code"`
	Turns                 int64          `json:"turns"`
	InputTokens           int64          `json:"input_tokens"`
	OutputTokens          int64          `json:"output_tokens"`
	TotalTokens           int64          `json:"total_tokens"`
	EndpointFamily        sql.NullString `json:"endpoint_family"`
	MetadataJson          string         `json:"metadata_json"`
	CachedInputTokens     sql.NullInt64  `json:"cached_input_tokens"`
	ReasoningOutputTokens sql.NullInt64  `json:"reasoning_output_tokens"`
	ModelContextWindow    sql.NullInt64  `json:"model_context_window"`
}
